### ISSUE TITLE
Special column structure: Ch. 4 p. 219 [10]

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#102]
Implement as two `<postTag>`s?

**Comment by BrettRey** [comment]
could they just be merged with a comma?
intransitive, monovalent

**Comment by nschneid** [comment]
p. 312 [49] is similar.

(Just noting these for now to fix later)

**Comment by nschneid** [comment]
sometimes with multiply nested curly braces, e.g. p. 486

**Comment by nschneid** [comment]
see #106

**Comment by nschneid** [comment]
- [ ] p. 219 [10]: column headers missing
- [ ] p. 312 [49]: column headers missing
- [ ] p. 486: complicated semi-nested braces; probably special-case this one

**Comment by nschneid** [comment]
Actually, when columns contain feature values (postTags), and their headers name the feature, I'm not sure there's a good way to represent it in YAML. It would have to be _preTag: postTag_ pairings. Probably not worth the effort.
