### ISSUE TITLE
Guidelines: add example of subjectless clausal complement

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#112]
so we specify there is a subordinate Clause, not just a VP

**Comment by BrettRey** [comment]
As in _so_ "for the purpose of" not "well, then"?

**Comment by nschneid** [comment]
This came up in a discussion of verb complement clauses: e.g. "try opening the door". It would be good to make explicit that "opening the door" is a Clause, not just a VP. (The guidelines have some examples with complements of auxiliaries but those have other stuff going on.)

**Comment by BrettRey** [comment]
Like this?
[try-opening-the-door.pdf](https://github.com/user-attachments/files/15795150/try-opening-the-door.pdf)

**Comment by nschneid** [comment]
Yep thanks

**Comment by BrettRey** [comment]
Added in 4.7.2
