### ISSUE TITLE
move punctuation tokens to following token?

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#113]
Policy in original CGELBank:

<img width="500" alt="image" src="https://github.com/nert-nlp/cgel/assets/985263/244519bd-0169-4988-8409-ee042ad0c758">

It occurs to me that most common punctuation marks (commas, periods) are written orthographically with the previous word. It is less intuitive to put them in the subsequent-word node, and the tree visualization looks strange:

<img width="412" alt="image" src="https://github.com/nert-nlp/cgel/assets/985263/6e0d5ae1-4374-47ca-a315-edc623c862b9">

Nodes with punctuation are:

- `(V :p "(" :t "microwaved" :l "microwave" :xpos "VBN")`
- `(Adj :p "?" :p ")" :p "," :t "heartless")`
- `(Adj :p "," :t "tiny")`
- `(N :t "dogs" :l "dog" :p "...")`

Suggested new policy: all `:p` annotations will group with the **preceding word**, except (a) punctuation tokens containing "(", "[", and any series of punctuations following one of those, and (b) sentence-initial punctuation.

Under the new policy, the above sentence would have

- `(V :p "(" :t "microwaved" :l "microwave" :xpos "VBN" :p "?" :p ")" :p ",")`
- `(Adj :t "heartless")`
- `(N :t "salsa" :p ",")`
- `(Adj :t "tiny")`
- `(N :t "dogs" :l "dog" :p "...")`

Logically quotes could be treated like open parens/brackets, but because `"` and `'` are ambiguous, maybe we shouldn't go there.

Thoughts? @BrettRey @bwaldon

**Comment by nschneid** [comment]
PR implementing this: #114

**Comment by BrettRey** [comment]
I have no objections

**Comment by nschneid** [comment]
Updated guidelines—hope these are clearer:

<img width="442" alt="image" src="https://github.com/nert-nlp/cgel/assets/985263/3d196844-7151-4ab7-ac68-d3f83b5bc876">
<img width="442" alt="image" src="https://github.com/nert-nlp/cgel/assets/985263/e1ebe7f6-d42a-4b6a-998b-1c0905a0e53e">
