### ISSUE TITLE
"from the waist up"

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#130]
Uttered while having a photo taken: "I like from the waist up."

Is this analogous to the double complementation in "from Boston to Providence", where "from" licenses two complements ("Boston" and "to Providence") (p. 641)? And is the NP complement an object?

```lisp
(PP
    :Head (P :t "from")
    :Obj (NP [the waist])
    :Comp (PP
        :Head (P :t "up")))
```

**Comment by BrettRey** [comment]
I think it is analogous and that the NP complement must be an object.

**Comment by nschneid** [comment]
Updated the CGELBank docs to mention this.
