### ISSUE TITLE
Det+Mod coordination

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#132]
My first attempt, treating it as a delayed Nom:

<img width="759" alt="image" src="https://github.com/user-attachments/assets/5070144b-68fd-4250-b69c-6ffede9e6255">

Does this look right? There is a validation error but maybe the validator is too strict.

**Comment by nschneid** [comment]
Based on the fact that an AdjP can have a postnucleus—(72) in our guidelines, "as old as or older than me"—I would revise the category of the PredComp to NP.

**Comment by BrettRey** [comment]
Yes, I agree with PredComp:NP. Otherwise, looks good.
