### ISSUE TITLE
double P stranding

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#134]
Thoughts on this tree for "the kind of friend you always have something to talk about with"?

<img width="490" alt="image" src="https://github.com/user-attachments/assets/9415e981-21b6-4f86-adef-56a7c2a27dfe">

I wasn't sure about (i) the "something" DP as a gap filler and (ii) the placement of the with-PP. I don't think you can reverse the two PPs:

- *the kind of friend you always have something to talk with about

which may indicate something about the structure (is the with-PP a Mod perhaps?).

**Comment by nschneid** [comment]
twitter.cgel has "It's giving a pot of money that is looking for somewhere to go, something to do." with the same treatment of "something" + infinitival relative clause. So never mind about that part of the question.

**Comment by BrettRey** [comment]
I agree with your analysis.

**Comment by nschneid** [comment]
There was some discussion by email but no clear conclusion, so let's go with the above analysis.
