### ISSUE TITLE
'become' and PredComp vs. Obj

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#139]
Clearly "angry" or "a teacher" is a PredComp with "become":

- He became **angry**.
- He became **a teacher**.

But what about:

- They lived in what would become **Vichy France**.
- **the change** that we should become

Should we say that all internal NP complements of "become" are automatically PredComp, or can some of them be Obj?

**Comment by nschneid** [comment]
Looking at the tests in pp. 253-254, I don't see any reason these can't all be considered PredComps, but just wanted to be sure I'm not missing something.

**Comment by bwaldon** [comment]
I agree (after having reviewed the tests)

**Comment by BrettRey** [comment]
Yes, I also don't see why they wouldn't be PredComps
