### ISSUE TITLE
"as" + gerund-participial clause: is the clause PredComp or Comp?

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#144]
_As_ "is the prepositional analogue of the verb _be_" (p. 636), so it normally licenses a PredComp. But I am not sure about

- I regard the solution as being satisfactory.

where _being_ is explicit. Is the being-satisfactory clause just a Comp and satisfactory is the PredComp within it?

**Comment by BrettRey** [comment]
I'd say that just as _he's being difficult_ doesn't have _being difficult_ as a PredComp, nor should _as being difficult_.
