### ISSUE TITLE
Missing token

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#17]
https://github.com/nert-nlp/cgel/blob/6ec79b44eb1fa918c46afae354f37ef26a870d5a/datasets/twitter_cgel.txt#L1148

**Comment by nschneid** [comment]
and 

https://github.com/nert-nlp/cgel/blob/6ec79b44eb1fa918c46afae354f37ef26a870d5a/datasets/twitter_cgel.txt#L1353

`(P)` and `(Nom)` in

**Comment by nschneid** [comment]
https://github.com/nert-nlp/cgel/blob/7ea4cd91c55f0d97646d1f8d256dffa623fd0c9c/datasets/ewt_cgel.txt#L1036

https://github.com/nert-nlp/cgel/blob/7ea4cd91c55f0d97646d1f8d256dffa623fd0c9c/datasets/ewt_cgel.txt#L1843

https://github.com/nert-nlp/cgel/blob/7ea4cd91c55f0d97646d1f8d256dffa623fd0c9c/datasets/ewt_cgel.txt#L2124

https://github.com/nert-nlp/cgel/blob/7ea4cd91c55f0d97646d1f8d256dffa623fd0c9c/datasets/ewt_cgel.txt#L2197

https://github.com/nert-nlp/cgel/blob/7ea4cd91c55f0d97646d1f8d256dffa623fd0c9c/datasets/ewt_cgel.txt#L4330

https://github.com/nert-nlp/cgel/blob/7ea4cd91c55f0d97646d1f8d256dffa623fd0c9c/datasets/ewt_cgel.txt#L4327

etc.

**Comment by aryamanarora** [comment]
> `(P)` and `(Nom)` in
> 
> https://github.com/nert-nlp/cgel/blob/7ea4cd91c55f0d97646d1f8d256dffa623fd0c9c/datasets/ewt_cgel.txt#L363-L368

The (P) one is missing in the original text, typo for "as". How should we deal with that?

(Nom) is fine, that's because of the fused head

**Comment by nschneid** [comment]
Hmm, maybe introduce more info: `:correct "as"`

There are other cases as well—I saw "our" as a P, which looked wrong until I realized it was a typo of "out"
