### ISSUE TITLE
Tokenization?

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#21]
https://github.com/nert-nlp/cgel/blob/1d68c0958993002f8a9a0a59f23b7300d482c6e3/analysis/cgel.conllu#L32

**Comment by nschneid** [comment]
In UD there is the distinction between `fixed` for grammaticalized functional MWEs and `flat` for personal names etc. But I think I'd keep things simple and just go with `Flat`. The grammaticalized functional ones can probably be listed if anyone cares to distinguish them.

**Comment by nschneid** [comment]
We now have guidelines for different types of flat/morphologically derived multiword expressions.

Remaining cases:

Unregistered complex fixed V lexeme: snow blowing
Unregistered complex fixed N lexeme: needs to be proofread by a native speaker
Unregistered complex fixed N lexeme: requires L1 regularization
Unregistered complex fixed Adj lexeme: EPM like

@BrettRey should we just hyphenate "snow-blowing" and "EPM-like" and treat as one word? Or is there a reason to characterize the morphological derivation?

**Comment by nschneid** [comment]
- "snow blowing": This is a compound verb of the N+V type (pp. 1660-1661). Compound verbs are described as fairly rare lexical innovations. So I'd be inclined to just hyphenate it as a single token.
- "EPM like": -like is fairly productive (p. 1711), and could apply to a multiword expression ("Barack Obama-like"). What do you think of treating "like" as an Adj heading an AdjP, with NP as Mod?

**Comment by BrettRey** [comment]
Those both sound like good solutions
