### ISSUE TITLE
Constraints on gaps/coindexation

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#38]
We should validate that coindexation is handled properly. At present the rules are as follows:

- No element (gap or proper constituent) is allowed more than one coindexation variable.
- A gap need not be coindexed (for now; this may change).
- Every coindexation variable must be attached to at least one gap and at least one proper constituent.

Examples:
- Gap without index
![image](https://user-images.githubusercontent.com/985263/181933784-876160aa-5c84-4d04-b5b3-45e97329e8a1.png)

- Multiple coindexed gaps 
![image](https://user-images.githubusercontent.com/985263/181933350-c814d0b7-79e1-43a2-a0ca-4f71e3d5bac5.png)

![image](https://user-images.githubusercontent.com/985263/181933467-4134eb1b-e840-4960-bda3-2ceafe1371c9.png)

- Multiple coindexed non-gap constituents (e.g. integrated relativizer "which"/"who" + its antecedent, as well as the gap)
![image](https://user-images.githubusercontent.com/985263/181926037-100f6bba-4ad0-42ef-8016-06617dfd7666.png)

**Comment by nschneid** [comment]
Usually an index variable should have 2 or 3 constituents. Validation now warns if more than 3: usually this is a variable reused by accident.

**Comment by nschneid** [comment]
Revised in guidelines and validator. Now:

- Every gap must be coindexed with exactly one overt constituent—which must be *phrasal* not lexical—and optionally other gaps as well
- Every coindexation variable must correspond to at least one gap

I.e. multiple overt constituents may NOT be coindexed.

**Comment by BrettRey** [comment]
looks good
