### ISSUE TITLE
Twitter tree errors

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#39]
- [x] ItBlowsMyMind-0 "someone who is both old enough": there should be a subject gap

- [x] Here-sThePaper-0 "people who read it": there should be a subject gap

- [x] WasDiscoveringThatICould-0 coindexation is weird, I'm not sure of the correct analysis. Note the `y` on "it", "what", and "R"
![image](https://user-images.githubusercontent.com/985263/181934408-221ac527-2a9b-4178-a4ea-4c6129c53e30.png)

**Comment by nschneid** [comment]
For an integrated relative clause (`:Mod Clause_rel`), setting aside free relatives, it is always the case that the sister-head should be coindexed with the gap (+ pronominal relativizer if present)?

I see exceptional EWT cases 
- "the [[wine flight_i] [we chose --_i]]". Should that be [wine flight]_i?
- "the [benefit [fund [raiser [we are holding --_i]]]]". Should that be [[benefit [fund raiser]]_i [we are holding --_i]]?

In Twitter
- "the [Navy Seal] [who killed...]" I think should be "the [Navy Seal]_i [who_i [--_i killed...]]"
- "Japanese farmers who use..."
- "who I'm writing a [book_y [about --_x] [that [--_y will be released]]]": I think should be [book [about --_x]]_y
- "What a remarkable claim [to make]": not Clause_rel, is it? This is like tough movement
- "[DP [D someone]_x] [NP [Nom who_x]] is both old enough..."
- "somewhere to go", "something to do": on token rather than its unary phrase
- "[kind of nonsense_x] that..."

**Comment by nschneid** [comment]
> * "What a remarkable claim [to make]": not Clause_rel, is it? This is like tough movement

@BrettRey

**Comment by BrettRey** [comment]
agreed

**Comment by nschneid** [comment]
How about Comp_ind:

```lisp
(NP
    :Mod (AdjP
        :Head (Adj :t "what"))
    :Head (NP
        :Det (DP
            :Head (D :t "a"))
        :Head (Nom
            :Head (Nom
                :Mod (AdjP
                    :Head (Adj :t "remarkable"))
                :Head (x / Nom
                    :Head (N :t "claim")))
            :Comp_ind (Clause
                :Head (VP
                    :Marker (Sdr :t "to")
                    :Head (VP
                        :Head (V :t "make" :p "!")
                        :Obj (x / GAP)))))))
```

**Comment by BrettRey** [comment]
That occurred to me too, and I think you're right.
