### ISSUE TITLE
Subordinate clause PPs: Mod vs. Supplement

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#42]
Here are cases of clauses introduced by *if*, *because*, *when*, and *while*:

Twitter
- Mod: An abstract syntax tree is abstract **because it is a mathematical object that has certain structure by its very nature**
- Mod: **If your usage argument is well-reasoned**, it's not pedantry!
- Mod: I bet this tweet would have been more popular **if I had twitten it 11 months later**.
- Mod: **when we cook** it tastes good
- Mod: you all make a tree **while I do emoji reacts like a syntax ghost**

EWT
- Mod: they will move **if they get too warm**
- Mod: **If you have any questions or require any assistance at all,** please contact Hope Duncan
- Mod: **If you ever go on a cruise ship,** you will be required to attend a SOLAS muster drill
- Supplement: **If ever in Sicily** please take the time to visit Anna Maria Jose Mudo
- Supplement: **if my garage door needs to be repaired,** I will be calling A CLASS Garage Doors
- Supplement: I also hope no one feels any obligation to download, **especially if you have an internet connection as slow mine**
- Supplement: **If I had time to drive to Tacoma before they closed during the work week**, I would
- Supplement: **If that is the case** then acupuncture isn't going to hurt him.
- Supplement: I rarely listen to the news or to what politicians or lawyers say **because so many tell lies**
- Supplement: I'm hoping the bakers continue to do their baking out of another place, **because it would be a shame not to have these cakes any longer**
- Supplement: Not that there is anything wrong with that **because they also employ local people that live and shop in the area**

@BrettRey the Mod ones all look fine to me; is there a need for Supplement with these PPs?

**Comment by nschneid** [comment]
I guess "especially if" feels like a Supplement.

What about "if...then" pairs?

**Comment by BrettRey** [comment]
The differences are not obviously motivated, but I don't know what to do with this, though I understand we need to do something. Is there somebody whose input you would trust?

**Comment by nschneid** [comment]
Looking at p. 1360, my preference would be to default to Mod for ordinary time/place/manner/reason/condition PP adjuncts in a clause, and reserve Supplement for speech act modifiers as well as interpolations/appendages that serve as addenda to the information in the clause's regular structure. I think "especially if" qualifies as an addendum.

But I am not positive about all these cases. Feel free to take this up with GKP if you like.

**Comment by BrettRey** [comment]
I'm happy to go with these. Can you add them to the documentation?

I've tried talking about it with Geoff, and he's completely Delphic on the issue.
