### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#43]
- [x] "both X and Y": "both" should project a DP right? [[Marker:DP [D both]] [old enough]] [and ...]
- [x] "along with": right now, [PP [Mod:PP [P along]] [Head:PP with...]]. Do we need to treat "along" as a special P-modifying-PP, or could it be a head that takes with-PP complements?
- [x] "So that's what I'm particularly interested in seeing if is true." Right now it is a MultiSentence coordination of [Clause [PP So]] and the rest. Better to make "so" an Adv? Int? Coordinator? I don't see this as two clauses.
- [x] Should a directional PP premodifier project its own nested PP? Inconsistent: "(come) back out", "(come) over to (the Enron building)"
- [x] Are two Mods allowed at the same level? If not, what to do with: "[At 3:15 am] [on night # 2], the fire alarm and strobe light activated in my room."
- [x] What is the proper use of Nom layers in compounds? An extreme example being "huge IKEA plastic storage box lid".
- [x] structure of the idiom "talk down to" someone? [PP down to]? [Comp:PP down] [Comp:PP to]?

@BrettRey

**Comment by BrettRey** [comment]
You're dredging up all these examples I struggled with. :-)

1. _both_ should project a DP
2. Perhaps we could add _along with_ to the complex prepositions list (hints along those lines in fn 25, p. 1305)
3. Is that the whole thing? Not two clauses. Is this like (45) in  section 5.2.2, root level?
4. I'm not sure. I can't think of a good way to test whether it's a series of mods in the VP or nested PPs.
5. I think the answer is no. Perhaps layered.
6. `[NP
	[\Det{NP}[my, roof]]
	[\Head{Nom}
		[\Mod{AdjP}[huge,roof]]
		[\Head{Nom}
			[\Mod{Nom}[\Head{N}[IKEA]]]
			[\Head{Nom}
				[\Mod{Nom}[\Head{N}[plastic]]]
				[\Head{Nom}
					[\Mod{Nom}
						[\Mod{Nom}[\Head{N}[storage]]]
						[\Head{Nom}[\Head{N}[box]]]
					]
					[\Head{Nom}
						[\Head{N}[lid]]
					]
				]
			]
		]
	]
]`

**Comment by nschneid** [comment]
> * Perhaps we could add _along with_ to the complex prepositions list (hints along those lines in fn 25, p. 1305)

Syntactically how is it different from _out of_? In general CGEL prefers not to use complex prepositions, but I am not sure how to determine the exceptions.

**Comment by nschneid** [comment]
Decision: "So that's what" we can treat So as a Coordinator.

**Comment by nschneid** [comment]
Another PP question: what is the best structure for the idiom "talk down to" someone?

**Comment by BrettRey** [comment]
Two PP complements, I think.

**Comment by BrettRey** [comment]
from Geoff "I think there will be plenty of cases where a PP can be interpreted either as a complement to a preceding preposition or as an independent modifier in the VP."

**Comment by nschneid** [comment]
That is re: "along with"?

**Comment by BrettRey** [comment]
yes, or _came_ [_back_] [_out of the cave_]

**Comment by nschneid** [comment]
Gonna treat "along with" like "out of", with a note that the structure is unclear.

**Comment by BrettRey** [comment]
sure

**Comment by nschneid** [comment]
"On Tuesday at 3:15, I was awoken...": This doesn't feel like asyndetic coordination to me, or like a supplement, nor does "On Tuesday" + "at 3:15, I was awoken" seem like a sensible constituent structure. I'm thinking it is just typical to express a place or time with multiple PPs bunched together. The structure I hate the least would be a PP modifier within the full adjunct:

[Mod:PP [Head:PP On Tuesday] [Mod:PP at 3:15]]

though if it is ambiguous we should prefer attaching the 2nd PP within the object of the first preposition. Since "at" selects for a time, not a day, flipping the order would lead us to prefer the NP-internal modifier:

[Mod:PP [Head:PP At [3:15 [Mod:PP on Tuesday]]]]

**Comment by BrettRey** [comment]
I'm good with either of those
