### ISSUE TITLE
Should Head sister to a Mod always be a phrasal category (as opposed to a lexical category)?

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#44]
```
(VP
    :Mod (AdvP
        :Head (Adv :p "," :t "computationally"))
    :Head (V :p "-" :t "aided" :l "aid"))
```

vs.

```
(VP
    :Mod (AdvP
        :Head (Adv :t "well"))
    :Head (VP
        :Head (V :p "-" :t "reasoned" :l "reason")))
```

**Comment by nschneid** [comment]
@BrettRey

**Comment by BrettRey** [comment]
In an NP, yes (because of relative clauses). In other phrases, I'm happy to go either way.

**Comment by nschneid** [comment]
Why relative clauses?

**Comment by BrettRey** [comment]
So the co-index isn't recursive

**Comment by nschneid** [comment]
OK, so if there is a relative clause Mod it can't be under the Nom that is the immediate projection of the noun. Generalizing to all NPs, the noun must have a Nom projection that contains no Mods.

In terms of non-NPs, I'm torn between uniformity (like NPs, every lexical item always must have a phrasal projection with no Mods) vs. structural simplicity (only introduce a new Mod layer if necessary for binarization).

Structural simplicity makes for a slightly less parsimonious grammar: we need
VP → Mod:AdvP Head:V
VP → Mod:AdvP Head:VP
VP → Head:V Mod:PP
VP → Head:VP Mod:PP
and so on. But more unary productions (VP → Head:V) make the tree clunkier to read.

**Comment by nschneid** [comment]
BTW I notice that the SIEG trees are shallow w.r.t. Mods/Adjuncts: they do not introduce a separate layer. So CGELBank departs from that at least for NPs and when necessary for binarization.

**Comment by BrettRey** [comment]
see [3] on p. 1113

**Comment by nschneid** [comment]
Yes—where there is a relative clause. But in SIEGtrees3:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/985263/184918816-bf424051-dbd9-4720-9cdd-7c1b72352056.png">

<img width="367" alt="image" src="https://user-images.githubusercontent.com/985263/184918680-711ff4bc-a4dc-4361-8a21-d6c0778d195e.png">

**Comment by BrettRey** [comment]
The upper one, I think, should have the Nom. When it comes to no NPs, then, yes, number of branches wasn't something we were really thinking about. For the treebank, though I think it's a useful principle. You?

**Comment by BrettRey** [comment]
Oh, I see you explained above. I could go either way, but I prefer binarity when possible.

**Comment by BrettRey** [comment]
Also, the model theoretic approach of CGEL is, as I think you know, in direct opposition to generative rules like VP → Mod:AdvP Head:V. I don't know if this is more or less parsimonious in MT thinking.

**Comment by nschneid** [comment]
Decided: we should favor uniformity. Every lexeme should have a projection with no Mods. We can write a script to simplify for those who want shallower structures.
