### ISSUE TITLE
Finalize/add checks for fused structures

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#47]
including LaTeX generation

**Comment by nschneid** [comment]
and Clause vs. Clause_rel layering

**Comment by BrettRey** [comment]
My preference here is that a relative clause is a relative clause whether it includes a prenucleus or not. I would like to have both layers marked, but I understand that the information provided by marking one level also applies to the other level. Only wh-relatives have a prenucleus, so if we decide to mark only one level, then marking the lowest would provide the most consistency, I think.

**Comment by nschneid** [comment]
That would be the opposite of what was done in the Fusion of Functions paper, right? I am reluctant to change that without input from Jordan and Geoff.

**Comment by nschneid** [comment]
Per your email, we can mark both. This means that there should never be Clause_rel as Head of Clause, or vice versa, right? That's easy to check for.

**Comment by BrettRey** [comment]
right

**Comment by nschneid** [comment]
So our .cgel notation is kinda ugly right now when it comes to fusion. From tree 070:

```
        (Nom
            :Head-Prenucleus (x / NP
                :Det-Head (DP
                    :Head (D :t "what"))
                :Head (Nom))
            :Mod (Clause_rel
                :Mod (Clause_rel
                    :Subj (NP
                        :Head (Nom
                            :Head (N_pro :t "we")))
                    :Head (VP
                        :Head (V_aux :t "are" :l "be")
                        :Comp (Clause
                            :Head (VP
                                :Head (V :t "trying" :l "try")
                                :Comp (Clause
                                    :Head (VP
                                        :Marker (Sdr :t "to")
                                        :Head (VP
                                            :Head (V :t "do")
                                            :Obj (x / GAP))))))))))
```

We have determiner-head fusion in "what" (which I don't think we need, but that's a separate issue) and we have the fused relative. Right now the notation doesn't make the second parent edge explicit. In processing the data it is necessary to infer that

- Det-Head:DP is always followed by Head:Nom (possibly lacking explicit children), which is to be interpreted as a second parent of the DP
   * same for Mod-Head:X (where there may be several values of X)
   * and for Marker-Head:Coordinator
- Head-Prenucleus:X (typically X=NP) is always followed by Mod:Clause_rel, which is to be interpreted as a second parent of X.

The way I was originally thinking of making the co-parentage explicit is with a reentrancy, which would require assigning a variable to the shared Nom/Clause_rel. But we are already using variables for coindexation, so I fear this would be confusing.

Maybe we could signal a bit more explicitly that something special is going on, e.g. notate it as `:Head-Prenucleus`...`:Mod (^Clause_rel)` (the `^` signaling that the constituent should also be a parent of the preceding sister constituent).

Another option would be to split up the functions, so have an explicit `:Head` and `:Prenucleus` that would refer to the same constituent. But I'm not sure how to do that without new variables.

Or maybe we should leave it as is.

**Comment by nschneid** [comment]
OK here's an option that doesn't require new variables and makes formal sense: instead of

```
(x / NP
    :Det-Head (DP
        :Head (D :t "what"))
    :Head (Nom))
```

we always put the shared constituent at the deeper level, and note the function that actually attaches higher:

```
(x / NP
    :Head (Nom
        :Head, ^:Det (DP
            :Head (D :t "what"))))
```

This says that the Det part of Det-Head belongs not to the Nom but to the NP. (The use of `^` here is inspired by LFG.)

**Comment by nschneid** [comment]
@aryamanarora curious to hear your opinion too

**Comment by BrettRey** [comment]
I like it.

**Comment by nschneid** [comment]
In treetest.tex I worked out a way to display fusion with the `forest` package without dummy nodes or manual spacing:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/985263/186517983-b1edb0cb-8d84-4119-a2d4-faffbcd1f53a.png">
Will implement this for the tex-generation code once we have settled on the notation.

**Comment by BrettRey** [comment]
Excellent!

Just from a visual point of view, can the branch to Head-Prenucleus be oriented more towards _Head_?

**Comment by nschneid** [comment]
Fixed the latter. Not sure how to fix the former.

**Comment by BrettRey** [comment]
Now the bottom node in the Determiner-Head is separated.

Again, just visual, but perhaps the incoming nodes should always join (as in the Determiner-Head example above) or always point to the distinct parts.

**Comment by nschneid** [comment]
Yeah here it is now:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/985263/186534034-61dfbd85-730d-49c3-9273-194e34d2fa88.png">

**Comment by BrettRey** [comment]
OK, let's go with that.

**Comment by nschneid** [comment]
Decision: Let's go with 

```
(x / NP
    :Head (Nom
        :Det-Head (DP
            :Head (D :t "what"))))
```

which omits the empty terminals and is transparent w.r.t. the Python data structure, even though it requires some interpretation to understand the full linguistic representation. @aryamanarora will convert the data.

**Comment by aryamanarora** [comment]
Done!
