### ISSUE TITLE
Structure of extraposition

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#54]
There are 3 different analyses in play:
- Binary, low-attaching: SIEG2 p. 372 has the extraposed subj as a Complement in the VP.
- Binary, high-attaching: §3.4.4 of the guidelines currently has an outer Clause with the extraposed subj
- Ternary: in the data, ExtraposedSubj is on the same level as Subj

@BrettRey how should we resolve this?

**Comment by aryamanarora** [comment]
Agreed on binary, low-attaching (in VP)
