### ISSUE TITLE
Coindexing the gap of a bare relative

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#56]
We now say that a Mod can be sister to a noun (without requiring a unary Nom layer). Does that include relative clauses? If so, how to coindex the gap in "a person you know"? On the N directly?

**Comment by BrettRey** [comment]
Yes, I think that's CGEL's position. "co-indexed with _razor-blade_, the head of the nominal containing the relative clause as modifier." p. 59

**Comment by nschneid** [comment]
OK. Revised as follows:

<img width="344" alt="image" src="https://user-images.githubusercontent.com/985263/188901194-1c5d87d2-ad89-40b2-80ff-3e2f32aecb39.png">

Also elaborated on §4.3.
