### ISSUE TITLE
"well" as interjection

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#59]
https://simple.wiktionary.org/wiki/well gives

- Well, I guess I'm leaving now.

as an adverb, but most dictionaries (including PTB tag guidelines) call it an interjection. Should we follow suit? For me, at least, the above example makes no suggestion that things are "well": it has no element of approval and cannot be modified by "very". The mid-utterance continuation usage ("He said that, well, it wouldn't be appropriate") also feels like an interjection.

By contrast, the discourse expression "Very well" means something like "All right", with a flavor of 'things are OK/all taken care of'. I support Adv for that usage.

**Comment by BrettRey** [comment]
Yes, I think you're right. I'll make the change on Simple English Wiktionary.
