### ISSUE TITLE
Postnominal Mod:VP should be (nonfinite) clause?

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#60]
SIEG2 p. 323 "the doctor **performing the operation**" is described as a clause. But currently we have just a VP layer for "the suit **filed against the generators**", "a very difficult period **dealing with a family member's suicide**", etc.

I am more sympathetic to plain VP if it's prenominal, e.g. "**dining** room", "the **existing** budget".

**Comment by BrettRey** [comment]
These are gerund-participial clauses (CGEL p. 162)
