### ISSUE TITLE
Syntactic structure of ratios

### ISSUE THREAD

**Issue by BrettRey** [nert-nlp/cgel#70]
It seems to me that _we went 100 kilometres each day_ is expressing distances, while _we went 100 km/h_ is expressing a velocity. 
- Is this just a question of an NP modifier attaching to the VP or the NP, or is something else going on? 
- What about the _km per hour/an hour_ distinction?
- What about something like _a dollar an hour wage_?
- What about _we gave them each 100._ vs _we gave them 100 each._?
- Separate but related, what about _we gave them each/both/all 100_?

**Comment by nschneid** [comment]
In "fifty miles an hour", "an hour" is an NP functioning as post-head internal modifier (CGEL p. 446)

**Comment by BrettRey** [comment]
Thanks, for that. Went looking but didn't turn it up. So we go with post-head modifier for all cases above, including _them each/both/all_?

**Comment by nschneid** [comment]
I couldn't find a direct answer to post-head "each" (meaning 'apiece') in CGEL. The closest I could find was on p. 445: “one day more", post-head internal modifier.

**Comment by BrettRey** [comment]
Seems applicable.

**Comment by nschneid** [comment]
Re: _We gave them each/both/all 100_:

p. 427:

![image](https://user-images.githubusercontent.com/985263/227079470-3c1fa3f6-88e2-4239-abb9-9f516a358b7a.png)

p. 428:

![image](https://user-images.githubusercontent.com/985263/227079628-60c3e685-dc51-4e05-bc90-11a44819f66e.png)

I'm not sure what to make of this..."It's an insult to us each" is marked with an asterisk, but maybe it's only problematic for semantic reasons? Cf. "They will give $10 to us/them/you each".

**Comment by nschneid** [comment]
(These should be known as Mulan pronouns: "You'll bring honor to us all")
