### ISSUE TITLE
Evaluation: what if gap antecedent is in a unary rule?

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#77]
Right now, the gap is scored as correct if its antecedent *span* is correct. But technically this could mask an error where the predicted antecedent's unary ancestor or descendant is the true antecedent.

Should we require the antecedent's category to be correct for the gap to count as correct?

**Comment by BrettRey** [comment]
Could you provide some examples?

**Comment by nschneid** [comment]
Wait, I guess we do have an alignment of nodes between trees. So we can require that, if a predicted gap pGAP is aligned to gold gap gGAP, for it to count as correct, the antecedent of pGAP in the predicted tree is aligned to the antecedent of gGAP in the gold tree. I think.

**Comment by nschneid** [comment]
This is a stricter measure. For example, it penalizes cases which are conceptually similar but differ in the size of a unary edge chain as well as category; the following two `x` nodes are not aligned:

```lisp
:Prenucleus (x / NP
	:Head (Nom
		:DetHead (DP
			:Mod (AdvP
				:Head (Adv :t "how"))
			:Head (D :t "much"))))
```

```lisp
:Prenucleus (x / AdvP
	:Mod (AdvP
		:Head (Adv :t "how"))
	:Head (Adv :t "much"))
```

Because the alignment of unary edge chains is done based on category and function, if the categories of the Prenucleus nodes matched they would be aligned.

I think this is OK though: the gaps are not considered to be the same as the antecedent structures are significantly different.
