### ISSUE TITLE
Gap or no gap? prepositional passives, gerund-participial purpose modifiers in nominals

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#85]
Inspired by [this thread](https://ell.stackexchange.com/q/337175/139225), I was wondering how these preposition stranding examples should look in CGELBank.

- the photos have been looked at (prepositional passive)
- some photos for looking at

CGEL (pp. 1264-1265) notes that gerund-participial modifiers are similar in meaning to relatives (e.g. infinitival relative _some photos to look at_). But CGEL declines to call these relative because they cannot host a relative phrase (_some photos at which to look_ vs. _*some photos at which for looking_). I don't see a place where CGEL discusses such modifiers in relation to preposition stranding or gaps. Of course, the same question about gaps could be asked regarding non-prepositional cases like "some food for eating".

**Comment by nschneid** [comment]
An argument in favor of including gaps for these is that this is not really an intransitive preposition, but would appear to be intransitive it it were the only thing in the PP.

**Comment by nschneid** [comment]
Thinking more about the prepositional passive:

On the one hand, it would be strange to include a gap only for *prepositional* passives and not regular passives, especially since the VPs can be coordinated (_The issue has been looked **at** and discussed many times_).

And note that passive + Comp:PP-with-gap does not imply it's a prepositional passive. In _What was my cooking compared **to**?_ the stranding/gap arises from a WH-question (cf. _To what was my cooking compared?_). _Whoever was spoken **to** didn't convey the message_: gap is due to the fused relative right?

On the other hand, it would be a shame if our trees did not disambiguate prepositional passives from regular passives with intransitive PPs.

Interestingly, prepositional passives seem to resist moving the PP, unlike other PPs in the VP:

* The claim will be looked **into** by an expert before Thursday.
   - What will be looked into by an expert before Thursday?
   - *Into what will be looked by an expert before Thursday?
   - By whom will the claim be looked into before Thursday?
   - Before when will the claim be looked into by an expert?
* The subject has been written **about** by many authors.
   - What subject has been written about by many authors?
   - *About what subject has been written by many authors?
   - By whom has the subject been written about?

So I take it that the PP specific to the prepositional passive construction is not a regular PP complement: the preposition is "frozen" in position after the verb. Maybe it warrants a distinct function, e.g. PPsv? It would be a kind of internal Comp, along the lines of Particle.

@BrettRey?

**Comment by nschneid** [comment]
In the adnominal construction "some photos for looking at", I think there has to be a gap; it is not an extrasyntactic inference that "photos" functions as the thing looked at—though other purpose gerund-participials could be interpreted without a gap.

- You should find a partner for a collaboration. (No gap, though there is an inference about the semantic relationship between "partner" and "collaboration")
- You should find a partner for collaborating with __. (Cannot be interpreted as the partner helps you collaborate with someone else)
- ?*You should find a partner for collaborating. (Not as good because "collaborate" isn't transitive, though it sounds better if "collaborating" is construed as a general activity that parties are participating in with unspecified roles.)
- ?*You should recruit a friend for driving you to the airport. (interpretation: "friend" as subject of "driving")
- You should recruit a friend for driving to the airport - sounds OK to me with (i) "driving to the airport" as a general activity to be undertaken, without specific subject/object assignments, or (ii) with a direct object gap 'driving a friend to the airport' (imagine the sentence is about an Uber driver who needs the business)

**Comment by BrettRey** [comment]
I think one feature of the passive construction is that the head in question gives up an argument as opposed to leaving a gap. I don't believe that you find, for instance, resumptive pronouns in passives. _That's the one that I saw it_ sounds a bit odd, but for me *_The window was broken it_ is totally unacceptable, as is *_The book was referred to it_. Similarly, *_The proposal needs it evaluating by a specialist_ is not possible for me. In short, I don't passives leave gaps.

**Comment by BrettRey** [comment]
_Some photos for_ [_looking at \_\_ _] is a hollow gerund-participial licensed by _for_, and like other hollow non-finite clauses, it does indeed have a gap.

**Comment by BrettRey** [comment]
So you're saying, unless the PP is a Comp or a Part, our notation is ambiguous between intransitive or passive and that this is a problem. I guess it's also ambiguous between transitive or intransitive verbs:
- _The horse was **walked** around_ [transitive passive verb; intransitive P]
- _The horse was walked **around**_ [intransitive verb; passive intransitive P]

Are there not other constructions that are ambiguous or can't be searched for?

**Comment by BrettRey** [comment]
You're right, it applies to the clause, not the word. I was being imprecise. 

It seems to me that if we're interested in being able to identify a prepositional passive, then it would make most sense to mark the clause as such: Clause~PP~.

**Comment by nschneid** [comment]
Isn't there a possible ambiguity in terms of which preposition is the stranded one?

- We are being walked out **on** now

Marking the intransitive vs. stranded distinction would be more precise than marking the entire clause (though when we add clause types we may also want to mark passives etc.).

**Comment by BrettRey** [comment]
You have a point. Do we also mark stranding when there is a gap then? And what about elliptical stranding? 

Also P<sub>strand</sub> or PP<sub>strand</sub>?

**Comment by nschneid** [comment]
I think PP<sub>strand</sub>, because it's constructional rather than lexical, and because PP<sub>strand</sub> would have a different distribution from other PPs: occurring in relative clauses, interrogatives, for-PPs, etc.

Elliptical stranding: of PPs, or other kinds of constituents?

**Comment by BrettRey** [comment]
Agreed about PP<sub>strand</sub>. So all stranded PPs.

Others, such as _I don't want to_ or _You shoul_.

**Comment by nschneid** [comment]
But if lots of phrasal categories support stranding, then we may not want to subcategorize because it would mean too many new categories.

**Comment by BrettRey** [comment]
Yes, VP<sub>strand</sub>. As far as I can think (and searching CGEL), only PPs and VPs.

**Comment by nschneid** [comment]
Do you want to write this up in the guidelines? We can call it version 1.1.

Added a tree to the hollow clause section:

<img width="315" alt="image" src="https://github.com/nert-nlp/cgel/assets/985263/ddf9af7f-3329-44c1-bbc1-5f3c099db4cc">

**Comment by BrettRey** [comment]
Will do.

**Comment by nschneid** [comment]
Would a fused relative be considered to have stranding in both the prepositional and nonprepositional cases?

- whoever I ate lunch with
- whatever I consumed for lunch

**Comment by BrettRey** [comment]
You mean would the _consumed_ VP be VP<sub>strand</sub>? I'd say "no". Just elliptical stranding for verbs.

**Comment by nschneid** [comment]
I guess I'm hesitant to use PP_strand VP_strand if CGEL is really discussing two completely different notions of stranding: elliptical stranding on VPs vs. preposition stranding on PPs. Because gapping constructions that can leave a transitive preposition stranded can also leave a transitive preposition with an object gap, one could expect that to be called a stranded verb.

How about PP_pstr for preposition stranding vs. VP_estr for elliptical stranding?

**Comment by BrettRey** [comment]
Again, you make a good point. They are different, even if they both use "stranding". Perhaps we just mark the PPs. The VPs are recoverable from the fact that they don't have a complement.

**Comment by nschneid** [comment]
If elliptical stranding is equivalent to "VP consisting of V_aux or Sdr *to* with no complement", then yes, no need to subcategorize; we can just stick with PP_strand.

**Comment by BrettRey** [comment]
OK, I've updated the guidelines, and called it 1.1.

**Comment by nschneid** [comment]
Added a prepositional passive tree in 3.4.6.

Are there any other stranded preposition examples that should now have PP_strand?

**Comment by nschneid** [comment]
What about in 5.3.1: (65) "Mo gave me one before and Jo two after"? Would that be considered stranding? Also (69)

(71) "as old as -- or older than -- me"

**Comment by BrettRey** [comment]
I would not classify either of those as stranded.
