### ISSUE TITLE
Elliptical stranding with _to_

### ISSUE THREAD

**Issue by BrettRey** [nert-nlp/cgel#86]
CGEL doesn't consider the structure of examples like _I don't want to_, but about the only possibility is a VP with a marker and a gap for a head. This strikes me as terrible. Can we change _to_ to Aux?
Levine, R. D. (2012). Auxiliaries: _To_’s company. _Journal of Linguistics_, 48(1), 187–203. [https://doi.org/10.1017/S002222671100034X](https://doi.org/10.1017/S002222671100034X)

**Comment by nschneid** [comment]
I don't think we want to say the head is a gap. But we could say it's a fused Marker-Head, right? We already have those for "etc.".

**Comment by nschneid** [comment]
Why I favor the Marker-Head hack: I grant that there are arguments in favor of calling infinitive marker "to" an auxiliary, but a) it seems like it would cause terminological confusion to move away from CGEL and SIEG on this, and b) it would make the structure more complicated in the non-stranding case: per our lexical projection principle we'd then have to project a VP headed by "to".

**Comment by BrettRey** [comment]
OK, fused Marker-Head it is. I'll update the guidelines.
