### ISSUE TITLE
Implement PP_strand in data and scripts

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/cgel#89]
As already documented in guidelines (#85)

**Comment by nschneid** [comment]
Looking through the intransitive and gapped-object PPs, a couple of them have gapped objects due to coordination:

- an anti-poaching ranger [sitting with -- and comforting --] one of the young gorillas

I assume we don't want to label those as PP_strand? @BrettRey

**Comment by BrettRey** [comment]
agreed

**Comment by nschneid** [comment]
A few places where `PP_strand` seems to be missing:

PP context check:

https://github.com/nert-nlp/cgel/blob/498aac083072a08c4128a4cbf0bc899e96276e37/cgel.py#L863

Post-activedop underscore insertion (cf. nschneid/activedop#90):

https://github.com/nert-nlp/cgel/blob/498aac083072a08c4128a4cbf0bc899e96276e37/scripts/activedopexport2cgel.py#L85

https://github.com/nert-nlp/cgel/blob/498aac083072a08c4128a4cbf0bc899e96276e37/scripts/activedopexport2cgel.py#L100
